# -*- coding: utf-8 -*-
"""ฺBot Samathi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycY59i3uuwfD6RKR6P8AO6Zbrckn6dCV
"""

#@title เปิดใช้งาน Gemini API และคุณสมบัติของ ChatBot
import google.generativeai as genai

genai.configure(api_key="AIzaSyAL94E1WaxlpYhewI9sQlfhXoBo9fnRog4")

# Set up the model
generation_config = {
  "temperature": 1,
  "top_p": 0.95,
  "top_k": 0,
  "max_output_tokens": 8192,
  "stop_sequences": [
    "พอแล้ว",
  ],
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
]

system_instruction = "คุณคือ Chatbot ที่ไม่มีความรู้อะไรเลย แต่เข้าใจภาษาไทยได้ดี คุณจะเรียนรู้จากคำถามและจดจำการพูดคุย ถ้าคุณไม่รู้ก็จะถามว่าคืออะไร"

model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest",
                              generation_config=generation_config,
                              system_instruction=system_instruction,
                              safety_settings=safety_settings)

#@title ลงโปรแกรม install อ่านออกเสียง
!pip install gtts

#@title นำเข้าทรัพยากรที่จำเป็นในการอ่านออกเสียง
import os
import pandas as pd
from IPython.display import display
from IPython.display import Audio
from gtts import gTTS

You_Ark = "หัวข้อ 2.2.6 ฌานลึก อยู่หน้าที่ 77-79 ฌานลึกสามารถย่อขันธ์ 5 ได้ ย่อจนเป็นหัวเชื้อที่เข้มข้นของฌาน  การเลื่อนระดับของฌานจากรูปฌานเป็นอรูปฌานต้องมีลักษณะของฌานลึก 7 ข้อดังนี้ 1.กระแสจิต เมื่อผ่านจุดพลังอำนาจจะเกิดกระแส 2.เกิดพลังของจิตจากสมาธิตื้น 3.มีศูนย์รับอารมณ์แทนคล้ายเกราะกระจกป้องกันเสียงหรืออารมณ์ภายนอกที่จะมากระทบจิตได้ 4.วิญญาณ หรือตัวรู้จะถูกพลังจิตกำหนดไว้ให้ทำงานเพียงแค่ผู้รู้ไม่มีอารมณ์ 5.ความครอบครอง อรูปฌาน 5-6-7-8 ความเป็นเจ้าของฌาน 6.ความสงบ 7.ความย่อขันธ์ 5 กลั่นเป็นหัวเชื้อ" # @param {type:"string"}
convo.send_message(You_Ark)
print(convo.last.text)
tts = gTTS(convo.last.text, lang="th")
tts.save("botsound.mp3")

# เล่นเสียงโดยใช้ IPython.display.Audio
Audio("botsound.mp3", autoplay=True)